config/routes.rb
Coffeend::Application.routes.draw do
  root to: "root#root"
  resource :session, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create]
  namespace :api, :defaults => { :format => :json } do
    get 'user' => 'users#load'
    put 'user' => 'users#update'
    resources :users, :only => [:show]
    resources :hangouts, :only => [:create, :index, :destroy, :update]
    resources :coffee_shops, :only => [:index]
    resources :attendances, :only => [:create, :destroy]
    resources :comments, :only => [:create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeend</title>
<link href='http://fonts.googleapis.com/css?family=Esteban' rel='stylesheet' type='text/css'>
	<script src="http://maps.google.com/maps/api/js?key=AIzaSyB1q3CH-oShYFvreoy4yyQb-RqzzRKpg8o&sensor=false&libraries=places"></script>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="coffeend-background">
	<div class="container">

	<nav class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">Coffee Date</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="navbar-collapse-1">
		<ul class="nav navbar-nav">
			<%if logged_in? %>
				<li><a href="#">Home</a></li>
	      <li><a href="#new">New</a></li>
	      <li><a href="#coffeedates">Upcoming</a></li>
	      <li><a href="#profile">Profile</a></li>
	    <% end %>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<%if logged_in? %>
				<li><%=link_to("Logout", session_url, :method => :delete)%></li>
			<% else %>
				<li><a href="/users/new">Sign Up</a></li>
				<li><a href="/session/new">Login</a></li>
			<%end%>
		</ul>
	</div><!-- /.navbar-collapse -->
</nav>
	<%= yield %>
	</div>
</body>
</html>